### ISSUE TITLE
Relationship of time registers and compare registers in MTIMER device?

### ISSUE THREAD

**Issue by dkruckemyer-work** [riscv/riscv-aclint#6]
I can't find this explicitly stated, but if an MTIMER device points to both a physical mtime register and a bank of physical mtimecmp registers, is there a requirement that the physical mtime register be compared to the physical mtimecmp registers in the same MTIMER device?

For example, is the following allowed:

- MTIMER_0 points to mtime_A and mtimecmp_B
- MTIMER_1 points to mtime_B and mtimecmp_A
- mtime_A is compared with mtimecmp_A
- mtime_B is compared with mtimecmp_B

It seems that an MTIMER device should be required to point to the physical resources that are compared with each other, i.e. the above would be disallowed, and e.g. MTIMER_0 should point to mtime_A and mtimecmp_A.

**Comment by avpatel** [comment]
Good catch, let me try to add a statement to clarify this.

Regards,
Anup

**Comment by avpatel** [comment]
I have added a statement for clarification.

Can you please check the "Machine-level Timer Device" chapter in latest spec ?

Regards,
Anup

**Comment by dkruckemyer-work** [comment]
The wording looks good, except maybe "should" should be "must/shall" to express a required relationship?

**Comment by avpatel** [comment]
Okay, I will update tomorrow.

**Comment by avpatel** [comment]
It's updated now so closing this issue. Please re-open it's not addressed.
