### ISSUE TITLE
Typo in 3.2 Heading

### ISSUE THREAD

**Issue by jstormswdev** [riscv/riscv-aclint#8]
The heading for 3.2 should be: "3.2. MSIP Registers (Offsets: 0x00000000 - 0x00003FF8)". Not .....3FF**C** since that address is reserved and not a MSIP register.

**Comment by jstormswdev** [comment]
Also section 4.2 unless I am not getting something which is always possible.

**Comment by avpatel** [comment]
Thanks for catching these typos.  I have fixed it.
https://github.com/riscv/riscv-aclint/blob/main/riscv-aclint.adoc
